### ISSUE TITLE
Vipingo sprint meta issue

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope-workflows#243]
In a little less than a week, @walljcg will be presenting Ecoscope at a user conference in Vipingo Ridge, Kenya. I am creating this meta issue to keep a running list of work I am doing across various PRs to prepare for that. I have also created the branch [`cs/vipingo`](https://github.com/wildlife-dynamics/ecoscope-workflows/tree/cs/vipingo) to stage changes into, so that I can merge some of this work without creating conflicts in `main` for the remaining PRs open here that pre-date this work (which hopefully we can resolve in parallel). TODO list to follow shortly in a subsequent comment.

**Comment by cisaacstern** [comment]
- [ ] #216 
- [ ] Docker builds (three container types)
- [ ] Script runner service
    - can be additional package in `src/`). note that because the build directories can now run "themselves", there is less logic necessary for this than was previously the case. this should be a simple "checkout and pixi run"
- [ ] Wire script-runner into docker-compose (probably in `/compose` repo)
- [ ] Define prefix release process for core, ext-ecoscope, and script-runner packages
    - This is pretty clearly just an "on tag/release" workflow, like what has been established in ecoscope core. we can store the prefix api key as a GH secret and push directly from GH workflows.
- [ ] Top-level README
- [ ] CI check and/or pre-commit hook to ensure version synchronization for dependency sets that are duplicated in multiple places
